name: 'Terraform Apply'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-apply.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="openai_api_key=${{ secrets.OPENAI_API_KEY }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Get Outputs
        id: outputs
        run: |
          echo "backend_url=$(terraform output -raw backend_url)" >> $GITHUB_OUTPUT
          echo "frontend_url=$(terraform output -raw frontend_url)" >> $GITHUB_OUTPUT
          echo "acr_name=$(terraform output -raw container_registry_name)" >> $GITHUB_OUTPUT
          echo "acr_server=$(terraform output -raw container_registry_login_server)" >> $GITHUB_OUTPUT

      - name: Summary
        run: |
          echo "## Deployment Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Infrastructure deployed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### URLs" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend**: https://${{ steps.outputs.outputs.frontend_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Backend**: ${{ steps.outputs.outputs.backend_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Container Registry" >> $GITHUB_STEP_SUMMARY
          echo "- **Name**: ${{ steps.outputs.outputs.acr_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Server**: ${{ steps.outputs.outputs.acr_server }}" >> $GITHUB_STEP_SUMMARY
